/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.agentscope.core.message;

/**
 * 定义智能体对话中消息参与者的角色。
 *
 * <p>该枚举指定消息流中每条消息的来源或用途，支持正确的消息路由、处理和上下文管理。
 *
 * <p>消息角色：
 * <ul>
 *   <li>{@link #USER} - 来自人类用户或外部输入的消息</li>
 *   <li>{@link #ASSISTANT} - 由 AI 智能体或助手生成的消息</li>
 *   <li>{@link #SYSTEM} - 系统指令、提示或配置消息</li>
 *   <li>{@link #TOOL} - 包含工具执行结果或响应的消息</li>
 * </ul>
 *
 * <p>角色对于确定在与不同 LLM API 和工具系统交互时如何处理和格式化消息至关重要。
 */
public enum MsgRole {
    /**
     * User role for messages from human users or external inputs.
     *
     * <p>These messages typically contain user questions, commands, or input data
     * that the agent needs to process or respond to.
     */
    USER,

    /**
     * Assistant role for messages generated by AI agents or assistants.
     *
     * <p>These messages contain the agent's responses, reasoning, or actions
     * in response to user messages or system prompts.
     */
    ASSISTANT,

    /**
     * System role for system instructions, prompts, or configuration messages.
     *
     * <p>These messages typically contain setup instructions, context information,
     * or system-level directives that guide agent behavior.
     */
    SYSTEM,

    /**
     * Tool role for messages containing tool execution results or responses.
     *
     * <p>These messages contain the output from tool executions, including
     * return values, error messages, or status information from external tools.
     */
    TOOL
}
